theme = "boo-berry"

[editor]
line-number = "relative"
shell = ["zsh", "-c"]
mouse = false
bufferline = "always"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"
