"$schema" = "https://starship.rs/config-schema.json"
add_newline = false
palette = "blackbeige"
format = "$directory$git_branch$git_status$character"
right_format = "$all"

[character]
vicmd_symbol = "[N](bold beige) >>>"
success_symbol = "[>](bold beige)"
error_symbol = "[>](bold red)"

[directory]
style = "bold beige"
read_only = " ó°Œ¾"
truncation_length = 3
truncate_to_repo = true
format = "[$path]($style)[$read_only]($read_only_style) "

[python]
symbol = "îœ¼"
format = "[${symbol}${version}]($style) "
style = "bold gray"

[nodejs]
symbol = "î´"
format = "[${symbol}${version}]($style) "
style = "bold gray"

[cpp]
symbol = "î˜"
format = "[${symbol}${version}]($style) "
style = "bold gray"

[rust]
symbol = "ó±˜— "
format = "[${symbol}${version}]($style) "
style = "bold beige"

[golang]
disabled = true

[git_branch]
format = "[$symbol$branch]($style) "
style = "bold beige"

[git_status]
style = "bold beige"
untracked = ""
modified = "[!$count](bold yellow)"
staged = "[+$count](bold gray)"
renamed = "[Â»$count](bold gray)"
deleted = "[âœ˜$count](bold red)"
ahead = "[â‡¡$count](bold beige)"
behind = "[â‡£$count](bold beige)"
diverged = "[â‡•â‡¡$ahead_countâ‡£$behind_count](bold beige)"

[hostname]
ssh_only = true
format = "ğŸŒ [$hostname]($style) "
style = "bold beige"

[username]
show_always = false
format = "[$user]($style) "

[cmd_duration]
min_time = 2000
format = "[$duration]($style) "
style = "bold gray"

[package]
disabled = true

[palettes.blackbeige]
background = "#0f0f14"
foreground = "#f8f8f2"
black   = "#0f0f14"
beige   = "#9c8d7e"
red     = "#ff5555"
gray    = "#a0a0a0"
yellow  = "#f1fa8c"
white   = "#f8f8f2"
comment = "#6272a4"
