"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
palette = "tokyonight"

format = """$directory$character"""
right_format = """$all"""


[character]
vicmd_symbol = "[N] >>>"
success_symbol = '[âœ](bold #9ece6a)'
error_symbol = '[âœ](bold #f7768e)'

[directory]
style = "bold #7aa2f7"
read_only = " ó°Œ¾"
truncation_length = 3
truncate_to_repo = true

[python]
symbol = "îˆµ "
format = '[${symbol}${version}]($style) '
style = "#e0af68"

[nodejs]
symbol = "îœ˜ "
format = '[${symbol}${version}]($style) '
style = "#9ece6a"

[cpp]
symbol = "î˜ "
format = '[${symbol}${version}]($style) '
style = "#7aa2f7"

[rust]
symbol = "ó±˜— "
format = '[${symbol}${version}]($style) '
style = "#ff9e64"

[package]
symbol = "ğŸš€ " 
format = '[${symbol}${version}]($style) '
style = "#bb9af7"

[git_branch]
symbol = "ï˜ "
format = '[$symbol$branch]($style) '
style = "#f7768e"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold #bb9af7" 

untracked = ""
modified = '[!${count}](#ff9e64) '     
staged = '[+${count}](#9ece6a) '       
renamed = '[Â»${count}](#7aa2f7) '      
deleted = '[âœ˜${count}](#f7768e) '      

ahead = 'â‡¡${count}'
behind = 'â‡£${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'

[golang]
disabled = true

[cmd_duration]
min_time = 2000  
format = '[$duration]($style) '
style = "fg:#e0af68"

[palettes.tokyonight]
background = "#1a1b26"
foreground = "#c0caf5"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
orange = "#ff9e64"
