"$schema" = "https://starship.rs/config-schema.json"
add_newline = false
palette = "tokyonight"
format = "$directory$git_branch$git_status$character"
right_format = "$all"

[character]
vicmd_symbol = "[N] >>>"
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

[directory]
style = "bold blue"
read_only = " ó°Œ¾"
truncation_length = 3
truncate_to_repo = true
format = "[$path]($style)[$read_only]($read_only_style) "

[python]
symbol = "îœ¼"
format = "[${symbol}${version}]($style) "
style = "bold yellow"

[nodejs]
symbol = "î´"
format = "[${symbol}${version}]($style) "
style = "bold green"

[cpp]
symbol = "î˜"
format = "[${symbol}${version}]($style) "
style = "bold blue"

[rust]
symbol = "ó±˜— "
format = "[${symbol}${version}]($style) "
style = "bold orange"

[package]
disabled = true

[git_branch]
format = "[$symbol$branch]($style) "
style = "bold magenta"

[git_status]
style = "bold cyan"
untracked = ""
modified = "[!$count](bold orange)"
staged = "[+$count](bold green)"
renamed = "[Â»$count](bold blue)"
deleted = "[âœ˜$count](bold red)"
ahead = "[â‡¡$count](bold white)"
behind = "[â‡£$count](bold white)"
diverged = "[â‡•â‡¡$ahead_countâ‡£$behind_count](bold white)"

[golang]
disabled = true

[hostname]
ssh_only = true
format = "ğŸŒ [$hostname]($style) "
style = "bold magenta"

[username]
show_always = false
format = "[$user]($style) "

[cmd_duration]
min_time = 2000
format = "[$duration]($style) "
style = "bold yellow"

[palettes.tokyonight]
background = "#1a1b26"
foreground = "#c0caf5"
black      = "#15161e"
red        = "#f7768e"
green      = "#9ece6a"
yellow     = "#e0af68"
blue       = "#7aa2f7"
magenta    = "#bb9af7"
cyan       = "#7dcfff"
white      = "#a9b1d6"
orange     = "#ff9e64"
