
"$schema" = "https://starship.rs/config-schema.json"
add_newline = false
palette = "everforest"
format = "$directory$git_branch$git_status$character"
right_format = "$all"

[character]
vicmd_symbol = "[N] >>>"
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

[directory]
style = "bold blue"
read_only = " ó°Œ¾"
truncation_length = 3
truncate_to_repo = true
format = "[$path]($style)[$read_only]($read_only_style) "

[python]
symbol = "îœ¼"
format = "[${symbol}${version}]($style) "
style = "bold yellow"

[nodejs]
symbol = "î´"
format = "[${symbol}${version}]($style) "
style = "bold green"

[cpp]
symbol = "î˜"
format = "[${symbol}${version}]($style) "
style = "bold blue"

[rust]
symbol = "ó±˜— "
format = "[${symbol}${version}]($style) "
style = "bold orange"

[package]
disabled = true

[git_branch]
format = "[$symbol$branch]($style) "
style = "bold red"

[git_status]
style = "bold magenta"
untracked = ""
modified = "[!$count](bold orange)"
staged = "[+$count](bold green)"
renamed = "[Â»$count](bold blue)"
deleted = "[âœ˜$count](bold red)"
ahead = "[â‡¡$count](bold magenta)"
behind = "[â‡£$count](bold magenta)"
diverged = "[â‡•â‡¡$ahead_countâ‡£$behind_count](bold magenta)"

[golang]
disabled = true

[hostname]
ssh_only = true
format = "ğŸŒ [$hostname]($style) "
style = "bold magenta"

[username]
show_always = false
format = "[$user]($style) "

[cmd_duration]
min_time = 2000
format = "[$duration]($style) "
style = "bold yellow"

[palettes.everforest]
background = "#2b3339"
foreground = "#d3c6aa"
red        = "#e67e80"
green      = "#a7c080"
yellow     = "#dbbc7f"
blue       = "#7fbbb3"
magenta    = "#d699b6"
cyan       = "#83c092"
orange     = "#e69875"

