"$schema" = "https://starship.rs/config-schema.json"
add_newline = false
palette = "kanagawa_dragon"

format = """
$directory$git_branch$git_status
$character"""

right_format = "$python$nodejs$cpp$rust$cmd_duration$hostname$username"

[character]
vicmd_symbol = "[N](bold fg) >>>"
success_symbol = "[Â§](bold fg)"
error_symbol = "[Â§](bold red)"

[directory]
style = "bold fg"
read_only = " ó°Œ¾"
truncation_length = 3
truncate_to_repo = true
format = "[$path]($style)[$read_only]($read_only_style) "

[python]
symbol = "îœ¼"
format = "[${symbol}${version}]($style) "
style = "bold gray"

[nodejs]
symbol = "ó°™"
format = "[${symbol}${version}]($style) "
style = "bold gray"

[cpp]
symbol = "î˜"
format = "[${symbol}${version}]($style) "
style = "bold gray"

[rust]
symbol = "ó±˜— "
format = "[${symbol}${version}]($style) "
style = "bold fg"

[golang]
disabled = true

[git_branch]
format = "[$symbol$branch]($style) "
style = "bold fg"

[git_status]
style = "bold fg"
untracked = ""
modified = "[!$count](bold yellow)"
staged = "[+$count](bold gray)"
renamed = "[Â»$count](bold gray)"
deleted = "[âœ˜$count](bold red)"
ahead = "[â‡¡$count](bold fg)"
behind = "[â‡£$count](bold fg)"
diverged = "[â‡•â‡¡$ahead_countâ‡£$behind_count](bold fg)"

[hostname]
ssh_only = true
format = "ğŸŒ [$hostname]($style) "
style = "bold fg"

[cmd_duration]
min_time = 2000
format = "[$duration]($style) "
style = "bold gray"

[palettes.kanagawa_dragon]
bg     = "#181616"
fg     = "#c5c9c5"
red    = "#c34043"
green  = "#76946a"
yellow = "#c0a36e"
blue   = "#7e9cd8"
purple = "#957fb8"
aqua   = "#6a9589"
gray   = "#727169" 
orange = "#ffa066"
