"$schema" = "https://starship.rs/config-schema.json"
add_newline = false
palette = "blackred"
format = "$directory$git_branch$git_status$character"
right_format = "$all"

[character]
vicmd_symbol = "[N] >>>"
success_symbol = "[>](bold red)"
error_symbol = "[>](bold red)"

[directory]
style = "bold red"
read_only = " Û∞åæ"
truncation_length = 3
truncate_to_repo = true
format = "[$path]($style)[$read_only]($read_only_style) "

[python]
symbol = ""
format = "[${symbol}${version}]($style) "
style = "bold yellow"

[nodejs]
symbol = ""
format = "[${symbol}${version}]($style) "
style = "bold green"

[cpp]
symbol = ""
format = "[${symbol}${version}]($style) "
style = "bold cyan"

[rust]
symbol = "Û±òó "
format = "[${symbol}${version}]($style) "
style = "bold orange"

[golang]
disabled = true

[git_branch]
format = "[$symbol$branch]($style) "
style = "bold magenta"

[git_status]
style = "bold magenta"
untracked = ""
modified = "[!$count](bold yellow)"
staged = "[+$count](bold green)"
renamed = "[¬ª$count](bold cyan)"
deleted = "[‚úò$count](bold red)"
ahead = "[‚á°$count](bold blue)"
behind = "[‚á£$count](bold blue)"
diverged = "[‚áï‚á°$ahead_count‚á£$behind_count](bold blue)"

[hostname]
ssh_only = true
format = "üåê [$hostname]($style) "
style = "bold red"

[username]
show_always = false
format = "[$user]($style) "

[cmd_duration]
min_time = 2000
format = "[$duration]($style) "
style = "bold yellow"

[package]
disabled = true

[palettes.dracula]
background = "#282a36"
foreground = "#f8f8f2"
black      = "#21222c"
red        = "#ff5555"
green      = "#50fa7b"
yellow     = "#f1fa8c"
blue       = "#bd93f9"
magenta    = "#ff79c6"
cyan       = "#8be9fd"
white      = "#f8f8f2"
orange     = "#ffb86c"
purple     = "#bd93f9"
pink       = "#ff79c6"
comment    = "#6272a4"

[palettes.tokyonight]
background = "#1a1b26"
foreground = "#c0caf5"
black      = "#15161e"
red        = "#f7768e"
green      = "#9ece6a"
yellow     = "#e0af68"
blue       = "#7aa2f7"
magenta    = "#bb9af7"
cyan       = "#7dcfff"
white      = "#a9b1d6"
orange     = "#ff9e64"

[palettes.blackred]
background = "#0f0f14"
foreground = "#f8f8f2"
black   = "#0f0f14"
red     = "#ff5555"
green   = "#a0a0a0"
yellow  = "#f1fa8c"
blue    = "#bd93f9"
magenta = "#ff79c6"
cyan    = "#8be9fd"
orange  = "#ff6e6e"
white   = "#f8f8f2"
comment = "#6272a4"
